# Generated by Django 4.1 on 2024-01-13 09:34

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(null=True, upload_to=task.models.crew_image_file_path),
        ),
    ]
