# Generated by Django 4.1 on 2024-02-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_crew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(related_name='journeys', to='task.crew'),
        ),
    ]
